/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetorefeitorio;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static projetorefeitorio.LigaBD.ligacao;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author dbugalho
 */
public class Login1 extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    public static int verifica;

    public Login1() {
        initComponents();
        HoverBotao(Btn_Login);
        this.setSize(500, 300);
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ctxLogin = new javax.swing.JTextField();
        ctxPassword = new javax.swing.JPasswordField();
        Btn_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Label_Info = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(0, 204, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(560, 300));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\franc\\Documents\\NetBeansProjects\\ProjetoRefeitorio\\Projeto_alunos_Grupo2\\img\\usericon (1).png")); // NOI18N
        jLabel2.setToolTipText("");

        ctxLogin.setText("Jorge");
        ctxLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ctxLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ctxLoginFocusLost(evt);
            }
        });
        ctxLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxLoginActionPerformed(evt);
            }
        });

        ctxPassword.setText("123456789");
        ctxPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ctxPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ctxPasswordFocusLost(evt);
            }
        });
        ctxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxPasswordActionPerformed(evt);
            }
        });

        Btn_Login.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Login.setForeground(new java.awt.Color(182, 81, 38));
        Btn_Login.setText("ENTRAR");
        Btn_Login.setBorderPainted(false);
        Btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LoginActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\franc\\Documents\\NetBeansProjects\\ProjetoRefeitorio\\Projeto_alunos_Grupo2\\img\\cencalicon-removebg-preview (2).png")); // NOI18N

        Label_Info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Label_Info.setForeground(new java.awt.Color(182, 81, 38));
        Label_Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Info.setText("Cencal 2023 ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(109, 205, 184));
        jLabel3.setText("LOGIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(236, 436, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Label_Info)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ctxLogin)
                                .addComponent(ctxPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ctxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ctxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Label_Info)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctxLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxLoginActionPerformed
    public void mensagemErro(String erro) {
        JOptionPane.showMessageDialog(null, erro, "Erro Validação", JOptionPane.ERROR_MESSAGE);
    }

    public void mensageminfo(String info) {
        JOptionPane.showMessageDialog(null, info, "Login com Sucesso", JOptionPane.INFORMATION_MESSAGE);

    }    private void ctxLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctxLoginFocusGained
            // TODO add your handling code here:
            if (ctxLogin.getText().equals("Login")) {
                ctxLogin.setText("");
                ctxLogin.setForeground(new Color(153, 153, 153));
            }
    }//GEN-LAST:event_ctxLoginFocusGained

    private void ctxLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctxLoginFocusLost
        // TODO add your handling code here:
        if (ctxLogin.getText().equals("")) {
            ctxLogin.setText("Login");
            ctxLogin.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_ctxLoginFocusLost

    private void ctxPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctxPasswordFocusGained
        // TODO add your handling code here:
        if (ctxLogin.getText().equals("Password")) {
            ctxLogin.setText("");
            ctxLogin.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_ctxPasswordFocusGained

    private void ctxPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctxPasswordFocusLost
        // TODO add your handling code here:
        if (ctxLogin.getText().equals("")) {
            ctxLogin.setText("Password");
            ctxLogin.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_ctxPasswordFocusLost

    private void Btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LoginActionPerformed
        String login = ctxLogin.getText();
        String pass = ctxPassword.getText();
        try {
            if (VerificaLogin(login, pass)) {
                verifica = VerificaAdmin(login);
                switch (verifica) {
                    case 1:
                        mensageminfo("Bem-vindo " + login + "!");
                        MENU_S_Admin sa = new MENU_S_Admin();
                        this.setVisible(false);
                        sa.setVisible(true);
                        break;
                    case 2: {
                        mensageminfo("Bem-vindo " + login + "!");
                        MENU_A_Relatorio mo = new MENU_A_Relatorio();
                        this.setVisible(false);
                        mo.setVisible(true);
                        break;
                    }
                    case 3: {
                        mensageminfo("Bem-vindo " + login + "!");
                        MENU_AG_Relatorio mo = new MENU_AG_Relatorio();
                        this.setVisible(false);
                        mo.setVisible(true);
                        break;
                    }
                    default:
                        break;

                }
            } else {
                mensagemErro("Dados Incorretos!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login1.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_LoginActionPerformed

    private void ctxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    private boolean VerificaLogin(String login, String pass) throws SQLException {
        Connection con = ligacao();
        String sql = "SELECT * FROM admin WHERE Login= '" + login + "' AND Password= '" + pass + "'";
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        return rs.next();
    }

    private int VerificaAdmin(String login) throws SQLException {
        Connection con = ligacao();
        String sql = "SELECT * FROM admin WHERE Login= '" + login + "'";
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            int tipoAdmin = rs.getInt("Tipo_admin_id_tipoadmin");
            int atividadeAdmin = rs.getInt("Estado_atividade_idEstado_atividade");
            if (atividadeAdmin == 0) {
                mensagemErro("Admin Inativo");
                return 0;
            } else if (atividadeAdmin == 1) {
                switch (tipoAdmin) {
                    case 1:
                        return 1;
                    case 2:
                        return 2;
                    case 3:
                        return 3;
                    default:
                        break;
                }
            }
        }
        return 0;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Login;
    private javax.swing.JLabel Label_Info;
    private javax.swing.JTextField ctxLogin;
    private javax.swing.JPasswordField ctxPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
public static void HoverBotao(JButton botao) {
        botao.setBorderPainted(false);
        botao.setBorder(null);
        botao.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao.setBackground(new java.awt.Color(182, 81, 38));
                botao.setForeground(Color.white);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao.setBackground(Color.white);
                botao.setForeground(new java.awt.Color(182, 81, 38));
            }
        });
    }

    public static void HoverSair(JButton botao) {
        botao.setBorderPainted(false);
        botao.setBorder(null);
        botao.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao.setBackground(new java.awt.Color(255, 51, 51));
                botao.setForeground(Color.white);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao.setBackground(Color.white);
                botao.setForeground(new java.awt.Color(255, 51, 51));
            }
        });
    }
}
